# 数据库配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456

# mybatis 配置
mybatis:
  type-aliases-package: com.example.docker.mapper
  mapper-locations: classpath:mapper/*.xml
